### ISSUE TITLE
Add `author` to showcase entries

### ISSUE THREAD

**Issue by MattiSG** [openfisca/openfisca.org#114]
Following a workshop with reusers, several additional pieces of metadata emerged as relevant to add to the showcase entries. One of them is authorship metadata, allowing both promotion of author and identification as contact point for OpenFisca Core maintainers.

The metadata shall be structured this way:

```yaml
title: Your Reuse
website: https://openfisca.org/en/showcase/
author:
  type: individual|collective|ngo|research_center|business|local_government|national_government
  name: You
  contact: contact@openfisca.example
  link: https://openfisca.example
```

At least `author.name` and `author.link` should be made visible on the entry cards. The `author.contact` does not have to be publicly visible.

Partial examples can be found in the `reuses` branch.
